"use server"

import { and, asc, desc, eq, inArray, isNull, sql } from "drizzle-orm"
import { revalidatePath } from "next/cache"
import { db } from "@/db/client"
import { generationTasks, mockupCards, mockupDesignAssets, mockupGroupItems, mockupGroups, type MockupBindingConfig } from "@/db/schema"
import { getCurrentEnterpriseScope, requireEnterpriseContext } from "@/lib/auth/session"
import { getTemplate } from "@/lib/mockup/client"
import { loadMockupConfig } from "@/lib/mockup/settings"
import { parseMockupInfo } from "@/lib/mockup/task-info"
import type { MockupCardHistoryView, MockupHistoryBatch, MockupLibraryImage } from "@/lib/mockup/types"
import { validateReferenceImageUrls } from "@/lib/storage/reference-url"
import { prewarmExternalAssets } from "@/server/services/mockup-service"
import { addMockupDesignAssetSchema, createCardFromTemplateSchema, createMockupCardSchema, prewarmMockupAssetsSchema, renameMockupCardSchema, saveCardBindingsSchema } from "@/server/schemas/mockup"
import { apiErrMsg, groupVisibilityCondition, loadTemplateVisibilityMap, mockupUser, moduleDenied, snapshotGroupItem } from "./shared"


/* ═══════════════ 渲染卡片（个人工作区） ═══════════════ */

export async function createMockupCardAction(groupId: string): Promise<{
  ok: boolean
  error: string | null
  cardId: string | null
}> {
  const ctx = await requireEnterpriseContext()
  if (moduleDenied(ctx)) return { ok: false, error: "无权访问样机模块", cardId: null }
  const parsed = createMockupCardSchema.safeParse({ groupId })
  if (!parsed.success) {
    return { ok: false, error: "参数错误", cardId: null }
  }
  const scope = getCurrentEnterpriseScope(ctx)
  const cfg = await loadMockupConfig(scope.enterpriseId)
  if (!cfg) return { ok: false, error: "样机渲染服务未配置", cardId: null }

  const [group] = await db
    .select({ id: mockupGroups.id, name: mockupGroups.name })
    .from(mockupGroups)
    .where(
      and(
        eq(mockupGroups.id, parsed.data.groupId),
        eq(mockupGroups.enterpriseId, scope.enterpriseId),
        groupVisibilityCondition(ctx),
      ),
    )
    .limit(1)
  if (!group) return { ok: false, error: "大模板不存在或不可见", cardId: null }

  const [card] = await db
    .insert(mockupCards)
    .values({
      enterpriseId: scope.enterpriseId,
      userId: ctx.user.id,
      groupId: group.id,
      title: group.name,
    })
    .returning({ id: mockupCards.id })

  revalidatePath("/mockup")
  return { ok: true, error: null, cardId: card!.id }
}

/**
 * 从小模板直接建卡：复用（同人同模板的）自动建组，否则创建单成员套组
 * （autoGenerated=true，可见性随小模板），再建卡片。
 */



/**
 * 从小模板直接建卡：复用（同人同模板的）自动建组，否则创建单成员套组
 * （autoGenerated=true，可见性随小模板），再建卡片。
 */
export async function createCardFromTemplateAction(input: {
  templateId: string
  title?: string
}): Promise<{ ok: boolean; error: string | null; cardId: string | null }> {
  const ctx = await requireEnterpriseContext()
  if (moduleDenied(ctx)) return { ok: false, error: "无权访问样机模块", cardId: null }
  const parsed = createCardFromTemplateSchema.safeParse(input)
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? "参数错误", cardId: null }
  }
  const scope = getCurrentEnterpriseScope(ctx)
  const cfg = await loadMockupConfig(scope.enterpriseId)
  if (!cfg) return { ok: false, error: "样机渲染服务未配置", cardId: null }

  const user = mockupUser(ctx)
  let templateName = ""
  let visibility: "public" | "private" = "public"
  try {
    const detail = await getTemplate(cfg, parsed.data.templateId, user)
    const version = detail.latestVersion
    if (!version || !version.published) {
      return { ok: false, error: "该小模板未发布，不能创建卡片", cardId: null }
    }
    templateName = detail.name
    const visibilityMap = await loadTemplateVisibilityMap(cfg, user)
    visibility = visibilityMap.get(parsed.data.templateId)?.visibility ?? "public"
  } catch (err) {
    return { ok: false, error: apiErrMsg(err, "模板信息获取失败"), cardId: null }
  }

  // 复用本人同模板的自动建组
  const existing = await db
    .select({ groupId: mockupGroups.id })
    .from(mockupGroupItems)
    .innerJoin(mockupGroups, eq(mockupGroups.id, mockupGroupItems.groupId))
    .where(
      and(
        eq(mockupGroupItems.externalTemplateId, parsed.data.templateId),
        eq(mockupGroups.enterpriseId, scope.enterpriseId),
        eq(mockupGroups.ownerUserId, ctx.user.id),
        eq(mockupGroups.autoGenerated, true),
      ),
    )
    .limit(1)

  let groupId = existing[0]?.groupId
  if (!groupId) {
    const snap = await snapshotGroupItem(
      cfg,
      scope.enterpriseId,
      { templateId: parsed.data.templateId, sortOrder: 0 },
      user,
    )
    if (!snap.ok) return { ok: false, error: snap.error, cardId: null }
    const [group] = await db
      .insert(mockupGroups)
      .values({
        enterpriseId: scope.enterpriseId,
        ownerUserId: ctx.user.id,
        name: templateName,
        visibility,
        autoGenerated: true,
        sortOrder: 0,
      })
      .returning({ id: mockupGroups.id })
    groupId = group!.id
    await db
      .insert(mockupGroupItems)
      .values({ ...snap.item, groupId })
  }

  const [card] = await db
    .insert(mockupCards)
    .values({
      enterpriseId: scope.enterpriseId,
      userId: ctx.user.id,
      groupId,
      title: parsed.data.title?.trim() || templateName,
    })
    .returning({ id: mockupCards.id })

  revalidatePath("/mockup")
  return { ok: true, error: null, cardId: card!.id }
}



export async function deleteMockupCardAction(
  cardId: string,
): Promise<{ ok: boolean; error: string | null }> {
  const ctx = await requireEnterpriseContext()
  const scope = getCurrentEnterpriseScope(ctx)
  const deleted = await db
    .delete(mockupCards)
    .where(
      and(
        eq(mockupCards.id, cardId),
        eq(mockupCards.enterpriseId, scope.enterpriseId),
        eq(mockupCards.userId, ctx.user.id),
      ),
    )
    .returning({ id: mockupCards.id, groupId: mockupCards.groupId })
  if (deleted.length === 0) return { ok: false, error: "卡片不存在" }

  // 自动建组：最后一张卡片删除后清理空组（历史任务保留）
  const [group] = await db
    .select({ autoGenerated: mockupGroups.autoGenerated })
    .from(mockupGroups)
    .where(eq(mockupGroups.id, deleted[0]!.groupId))
    .limit(1)
  if (group?.autoGenerated) {
    const [left] = await db
      .select({ count: sql<number>`count(*)::int` })
      .from(mockupCards)
      .where(eq(mockupCards.groupId, deleted[0]!.groupId))
    if ((left?.count ?? 0) === 0) {
      await db.delete(mockupGroups).where(eq(mockupGroups.id, deleted[0]!.groupId))
    }
  }

  revalidatePath("/mockup")
  return { ok: true, error: null }
}



export async function renameMockupCardAction(input: {
  cardId: string
  title: string
}): Promise<{ ok: boolean; error: string | null }> {
  const ctx = await requireEnterpriseContext()
  const parsed = renameMockupCardSchema.safeParse(input)
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? "参数错误" }
  }
  const scope = getCurrentEnterpriseScope(ctx)
  const updated = await db
    .update(mockupCards)
    .set({ title: parsed.data.title, updatedAt: new Date() })
    .where(
      and(
        eq(mockupCards.id, parsed.data.cardId),
        eq(mockupCards.enterpriseId, scope.enterpriseId),
        eq(mockupCards.userId, ctx.user.id),
      ),
    )
    .returning({ id: mockupCards.id })
  if (updated.length === 0) return { ok: false, error: "卡片不存在" }
  revalidatePath("/mockup")
  return { ok: true, error: null }
}

/** 保存卡片上某小模板的绑定配置 */



/** 保存卡片上某小模板的绑定配置 */
export async function saveCardBindingsAction(input: unknown): Promise<{
  ok: boolean
  error: string | null
}> {
  const ctx = await requireEnterpriseContext()
  const parsed = saveCardBindingsSchema.safeParse(input)
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? "参数错误" }
  }
  const scope = getCurrentEnterpriseScope(ctx)

  const [card] = await db
    .select()
    .from(mockupCards)
    .where(
      and(
        eq(mockupCards.id, parsed.data.cardId),
        eq(mockupCards.enterpriseId, scope.enterpriseId),
        eq(mockupCards.userId, ctx.user.id),
      ),
    )
    .limit(1)
  if (!card) return { ok: false, error: "卡片不存在" }

  // 图片 URL 归属校验（防跨租户引用 / SSRF）
  const imageUrls = Object.values(parsed.data.bindings)
    .map((b) => b.imageUrl)
    .filter((u): u is string => Boolean(u))
  if (imageUrls.length > 0) {
    const err = await validateReferenceImageUrls(
      imageUrls,
      scope.enterpriseId,
    )
    if (err) return { ok: false, error: err }
  }

  const config = { ...((card.bindingConfig ?? {}) as MockupBindingConfig) }
  config[parsed.data.groupItemId] = parsed.data.bindings
  await db
    .update(mockupCards)
    .set({ bindingConfig: config, updatedAt: new Date() })
    .where(eq(mockupCards.id, card.id))

  revalidatePath("/mockup")
  return { ok: true, error: null }
}

/** 卡片历史批次（弹窗数据） */



/** 卡片历史批次（弹窗数据） */
export async function listCardHistoryAction(cardId: string): Promise<{
  ok: boolean
  error: string | null
  batches: MockupHistoryBatch[]
}> {
  const ctx = await requireEnterpriseContext()
  const scope = getCurrentEnterpriseScope(ctx)

  const [card] = await db
    .select({ id: mockupCards.id, groupId: mockupCards.groupId })
    .from(mockupCards)
    .where(
      and(
        eq(mockupCards.id, cardId),
        eq(mockupCards.enterpriseId, scope.enterpriseId),
        eq(mockupCards.userId, ctx.user.id),
      ),
    )
    .limit(1)
  if (!card) return { ok: false, error: "卡片不存在", batches: [] }

  const [items, tasks] = await Promise.all([
    db
      .select()
      .from(mockupGroupItems)
      .where(eq(mockupGroupItems.groupId, card.groupId))
      .orderBy(asc(mockupGroupItems.sortOrder)),
    db
      .select()
      .from(generationTasks)
      .where(
        and(
          eq(generationTasks.taskType, "mockup"),
          eq(generationTasks.enterpriseId, scope.enterpriseId),
          eq(generationTasks.userId, ctx.user.id),
          sql`${generationTasks.templateInfo}->>'cardId' = ${cardId}`,
        ),
      )
      .orderBy(desc(generationTasks.createdAt))
      .limit(120),
  ])
  const nameByItem = new Map(items.map((i) => [i.id, i.displayName]))

  const batchMap = new Map<string, MockupHistoryBatch>()
  for (const task of tasks) {
    const info = parseMockupInfo(task.templateInfo)
    if (!info) continue
    let batch = batchMap.get(info.batchTag)
    if (!batch) {
      batch = {
        batchTag: info.batchTag,
        createdAt: task.createdAt.toISOString(),
        tasks: [],
      }
      batchMap.set(info.batchTag, batch)
    }
    batch.tasks.push({
      taskId: task.id,
      groupItemId: info.groupItemId ?? "",
      displayName:
        nameByItem.get(info.groupItemId ?? "") ?? info.templateName ?? "样机",
      status: task.status,
      resultImage: task.resultImages?.[0] ?? null,
      errorMessage: task.errorMessage,
      createdAt: task.createdAt.toISOString(),
    })
  }
  return { ok: true, error: null, batches: [...batchMap.values()] }
}

/** 生成历史：按渲染卡片聚合当前用户全部生成图片（不含批量替换），按最近出图倒序 */



/** 生成历史：按渲染卡片聚合当前用户全部生成图片（不含批量替换），按最近出图倒序 */
export async function listAllCardHistoryAction(): Promise<{
  ok: boolean
  error: string | null
  cards: MockupCardHistoryView[]
}> {
  const ctx = await requireEnterpriseContext()
  const scope = getCurrentEnterpriseScope(ctx)

  const taskRows = await db
    .select()
    .from(generationTasks)
    .where(
      and(
        eq(generationTasks.taskType, "mockup"),
        eq(generationTasks.enterpriseId, scope.enterpriseId),
        eq(generationTasks.userId, ctx.user.id),
        sql`${generationTasks.templateInfo}->>'cardId' IS NOT NULL`,
      ),
    )
    .orderBy(desc(generationTasks.createdAt))
    .limit(500)

  const entries = taskRows
    .map((task) => ({ task, info: parseMockupInfo(task.templateInfo) }))
    .filter((e): e is { task: (typeof taskRows)[number]; info: NonNullable<ReturnType<typeof parseMockupInfo>> } =>
      e.info !== null && typeof e.info.cardId === "string",
    )

  const cardIds = [
    ...new Set(entries.map((e) => e.info.cardId as string)),
  ]
  const itemIds = [
    ...new Set(
      entries
        .map((e) => e.info.groupItemId)
        .filter((v): v is string => typeof v === "string"),
    ),
  ]
  const cardRows = cardIds.length
    ? await db
        .select({ id: mockupCards.id, groupId: mockupCards.groupId })
        .from(mockupCards)
        .where(inArray(mockupCards.id, cardIds))
    : []
  const groupRows = cardRows.length
    ? await db
        .select({ id: mockupGroups.id, name: mockupGroups.name })
        .from(mockupGroups)
        .where(
          inArray(
            mockupGroups.id,
            [...new Set(cardRows.map((c) => c.groupId))],
          ),
        )
    : []
  const itemRows = itemIds.length
    ? await db
        .select({ id: mockupGroupItems.id, displayName: mockupGroupItems.displayName })
        .from(mockupGroupItems)
        .where(inArray(mockupGroupItems.id, itemIds))
    : []

  const groupByCard = new Map(cardRows.map((c) => [c.id, c.groupId]))
  const nameByGroup = new Map(groupRows.map((g) => [g.id, g.name]))
  const nameByItem = new Map(itemRows.map((i) => [i.id, i.displayName]))

  const cardMap = new Map<string, MockupCardHistoryView>()
  for (const { task, info } of entries) {
    let card = cardMap.get(info.cardId!)
    if (!card) {
      const groupId = groupByCard.get(info.cardId!)
      card = {
        cardId: info.cardId!,
        groupName: groupId ? (nameByGroup.get(groupId) ?? "") : "",
        images: [],
        latestAt: task.createdAt.toISOString(),
        processing: false,
      }
      cardMap.set(info.cardId!, card)
    }
    if (task.status === "queued" || task.status === "processing") {
      card.processing = true
      continue
    }
    const resultImage = task.resultImages?.[0]
    if (task.status === "completed" && resultImage) {
      card.images.push({
        taskId: task.id,
        displayName:
          nameByItem.get(info.groupItemId ?? "") ?? info.templateName ?? "样机",
        resultImage,
        createdAt: task.createdAt.toISOString(),
      })
    }
  }

  // 过滤没有成功出图的卡片；latestAt 取最新一张出图时间（任务本身倒序，首张即最新）
  const cards = [...cardMap.values()]
    .filter((c) => c.images.length > 0)
    .map((c) => ({ ...c, latestAt: c.images[0]!.createdAt }))
  return { ok: true, error: null, cards }
}

/* ═══════════════ 图片库 ═══════════════ */



/* ═══════════════ 图片库 ═══════════════ */

export async function addMockupDesignAssetAction(input: {
  imageUrl: string
  fileName?: string
}): Promise<{ ok: boolean; error: string | null }> {
  const ctx = await requireEnterpriseContext()
  const parsed = addMockupDesignAssetSchema.safeParse(input)
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? "参数错误" }
  }
  const scope = getCurrentEnterpriseScope(ctx)
  const err = await validateReferenceImageUrls(
    [parsed.data.imageUrl],
    scope.enterpriseId,
  )
  if (err) return { ok: false, error: err }

  await db
    .insert(mockupDesignAssets)
    .values({
      enterpriseId: scope.enterpriseId,
      userId: ctx.user.id,
      imageUrl: parsed.data.imageUrl,
      fileName: parsed.data.fileName ?? null,
    })
    .onConflictDoNothing()
  return { ok: true, error: null }
}



export async function deleteMockupDesignAssetAction(id: string): Promise<{
  ok: boolean
  error: string | null
}> {
  const ctx = await requireEnterpriseContext()
  const scope = getCurrentEnterpriseScope(ctx)
  const deleted = await db
    .delete(mockupDesignAssets)
    .where(
      and(
        eq(mockupDesignAssets.id, id),
        eq(mockupDesignAssets.enterpriseId, scope.enterpriseId),
        eq(mockupDesignAssets.userId, ctx.user.id),
      ),
    )
    .returning({ id: mockupDesignAssets.id })
  if (deleted.length === 0) return { ok: false, error: "图片不存在" }
  return { ok: true, error: null }
}

/**
 * 素材预导入：把本项目存储图片提前转为外部渲染素材（填充 assetId 缓存）。
 * 图片库上传后与批量替换选图时调用，提交渲染时即免外部拉图等待；失败静默
 * 由调用方处理（提交路径仍有懒导入兜底）。
 */



/**
 * 素材预导入：把本项目存储图片提前转为外部渲染素材（填充 assetId 缓存）。
 * 图片库上传后与批量替换选图时调用，提交渲染时即免外部拉图等待；失败静默
 * 由调用方处理（提交路径仍有懒导入兜底）。
 */
export async function prewarmMockupAssetsAction(input: {
  imageUrls: string[]
}): Promise<{
  ok: boolean
  error: string | null
  results: Array<{ url: string; ok: boolean; error?: string }>
}> {
  const ctx = await requireEnterpriseContext()
  const parsed = prewarmMockupAssetsSchema.safeParse(input)
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? "参数错误", results: [] }
  }
  const scope = getCurrentEnterpriseScope(ctx)
  const cfg = await loadMockupConfig(scope.enterpriseId)
  if (!cfg) {
    return { ok: false, error: "样机渲染服务未配置", results: [] }
  }
  const err = await validateReferenceImageUrls(parsed.data.imageUrls, scope.enterpriseId)
  if (err) return { ok: false, error: err, results: [] }
  const results = await prewarmExternalAssets(cfg, scope.enterpriseId, parsed.data.imageUrls)
  return { ok: true, error: null, results }
}

/** 「我的上传」图片库列表（批量替换页选固定图用） */



/** 「我的上传」图片库列表（批量替换页选固定图用） */
export async function listMockupDesignAssetsAction(limit = 200): Promise<{
  ok: boolean
  images: MockupLibraryImage[]
}> {
  const ctx = await requireEnterpriseContext()
  const scope = getCurrentEnterpriseScope(ctx)
  const rows = await db
    .select()
    .from(mockupDesignAssets)
    .where(
      and(
        eq(mockupDesignAssets.enterpriseId, scope.enterpriseId),
        eq(mockupDesignAssets.userId, ctx.user.id),
      ),
    )
    .orderBy(desc(mockupDesignAssets.createdAt))
    .limit(Math.min(Math.max(limit, 1), 300))
  return {
    ok: true,
    images: rows.map((r) => ({
      id: r.id,
      imageUrl: r.imageUrl,
      fileName: r.fileName,
      createdAt: r.createdAt.toISOString(),
    })),
  }
}

/** 生成图资产（本人最近生图任务结果，图片库第二个 Tab；个人维度，与 /assets 口径一致） */



/** 生成图资产（本人最近生图任务结果，图片库第二个 Tab；个人维度，与 /assets 口径一致） */
export async function listGeneratedAssetsAction(limit = 200): Promise<{
  ok: boolean
  images: MockupLibraryImage[]
}> {
  const ctx = await requireEnterpriseContext()
  const scope = getCurrentEnterpriseScope(ctx)
  const rows = await db
    .select({
      id: generationTasks.id,
      resultImages: generationTasks.resultImages,
      createdAt: generationTasks.createdAt,
      completedAt: generationTasks.completedAt,
    })
    .from(generationTasks)
    .where(
      and(
        eq(generationTasks.enterpriseId, scope.enterpriseId),
        eq(generationTasks.userId, ctx.user.id),
        eq(generationTasks.status, "completed"),
        isNull(generationTasks.deletedAt),
        sql`${generationTasks.resultImages} IS NOT NULL`,
      ),
    )
    // 按完成时间倒序（新图在上）：图片是按完成时间产出的，若按提交时间
    // （createdAt）排序，先提交后完成的慢任务（如样机渲染）会排在更晚
    // 产出、用户感知更新的图下面；批量提交的同秒任务也可借此稳定排序
    .orderBy(
      sql`${generationTasks.completedAt} DESC NULLS LAST`,
      desc(generationTasks.createdAt),
    )
    .limit(Math.min(Math.max(limit, 1), 300))

  const images: MockupLibraryImage[] = []
  for (const row of rows) {
    for (const [idx, url] of (row.resultImages ?? []).entries()) {
      images.push({
        id: `${row.id}:${idx}`,
        imageUrl: url,
        fileName: null,
        createdAt: (row.completedAt ?? row.createdAt).toISOString(),
        taskId: row.id,
      })
      if (images.length >= limit) break
    }
    if (images.length >= limit) break
  }
  return { ok: true, images }
}

/* ═══════════════ 渲染提交与状态 ═══════════════ */


