/**
 * 样机渲染前端视图类型（page data / 轮询状态 / 弹窗数据）
 *
 * 由 server actions 组装下发，客户端组件只消费这些结构。
 */

import type { MockupBindingConfig } from "@/db/schema"

/** 绑定定义（加入套组时的快照，渲染前校验用） */
export interface MockupBindingDefView {
  bindingId: string
  type: "smartObject" | "text" | "pixel"
  layerId: number
  layerPath: string
  label: string
  required: boolean
  fit: "cover" | "contain" | "stretch"
  /** background=背景图层（本地扩展标记，套组快照/批量替换页用） */
  role?: "background"
}

export interface MockupGroupItemView {
  id: string
  displayName: string
  templateVersionId: string
  externalTemplateId: string
  canvasWidth: number | null
  canvasHeight: number | null
  bindings: MockupBindingDefView[]
  sortOrder: number
}

export interface MockupGroupView {
  id: string
  name: string
  ownerUserId: string
  ownerName: string
  visibility: "public" | "private"
  autoGenerated: boolean
  items: MockupGroupItemView[]
}

/** 小方块任务视图（卡片上每个小模板的最新渲染） */
export interface MockupSquareTaskView {
  taskId: string
  status: "queued" | "processing" | "completed" | "failed"
  /** 0-100（外部进度透传） */
  progress: number
  /** DOWNLOAD / RUN_JSX / EXPORT / UPLOAD */
  stage: string | null
  errorMessage: string | null
  resultImage: string | null
  batchTag: string
  createdAt: string
}

export interface MockupCardItemView extends MockupGroupItemView {
  /** 该方块最近一次渲染任务（跨全部批次，未渲染过为 null） */
  task: MockupSquareTaskView | null
  /** 必填绑定是否已配齐（渲染按钮可用性） */
  configured: boolean
  /** 历史任意批次曾成功出图（仅首次渲染规则：true = 不可再渲染/替换图层锁定） */
  hasRendered: boolean
  /** 该方块的 AI 生成结果（AI背景/AI渲染，最近在前，最多 8 张） */
  aiImages: MockupAiImageView[]
  /** 该方块有进行中的 AI 生图任务（页面加载/提交后均生效）→ 纯加载动画 */
  aiGenerating: boolean
}

export interface MockupCardView {
  id: string
  title: string
  groupId: string
  groupName: string
  createdAt: string
  updatedAt: string
  /** 卡片绑定配置（图层替换弹窗初始值） */
  bindingConfig: MockupBindingConfig
  items: MockupCardItemView[]
}

/** 图片库项 */
export interface MockupLibraryImage {
  id: string
  imageUrl: string
  fileName: string | null
  /** 上传/生成时间（ISO；图片库日期范围筛选用） */
  createdAt?: string
  /** 生成图 tab：来源任务（收藏/定位用） */
  taskId?: string
}

/** 页面初始数据 */
export interface MockupPageData {
  /** false = 企业未配置/未开通样机渲染（显示引导空态） */
  available: boolean
  costPerRender: number
  groups: MockupGroupView[]
  cards: MockupCardView[]
  designAssets: MockupLibraryImage[]
  creditsBalance: number
  /** 已完成但未落地的 AI背景任务（浏览器中途关闭的兜底，页面加载时续做） */
  pendingAiApplies: Array<{ taskId: string; cardId: string; groupItemId: string }>
  /** 进行中的 AI 生图任务（页面刷新后播种前端轮询：队列重试成功仍能自动套版） */
  pendingAiTasks: Array<{
    taskId: string
    aiKind: "background" | "render"
    cardId: string
    groupItemId: string
  }>
}

/** 模板管理-外部小模板列表项 */
export interface MockupExternalTemplateView {
  templateId: string
  name: string
  code: string
  status: string
  statusLabel: string
  published: boolean
  latestVersion: number
  /** 服务端是否有缩略图（false 时显示占位 + 生成按钮） */
  hasThumbnail: boolean
  /** 缩略图预签名直链（绝对地址，浏览器 <img> 直接加载；旧版 PS-API 无此字段时走代理路由） */
  thumbnailUrl?: string | null
  visibility: "public" | "private"
  /** 归属人（外部 ownerUserId；null=平台共享） */
  ownerUserId: string | null
  /** 归属人显示名（join users；平台共享为空） */
  ownerName: string | null
  createdAt: string
}

/** 模板管理-大模板列表项（含成员与统计） */
export interface MockupGroupManageView {
  id: string
  name: string
  visibility: "public" | "private"
  autoGenerated: boolean
  ownerUserId: string
  ownerName: string
  updatedAt: string
  cardCount: number
  items: Array<{
    id: string
    displayName: string
    externalTemplateId: string
    templateVersionId: string
  }>
}

/** 渲染结果 */
export interface RenderMockupResult {
  ok: boolean
  error: string | null
  batchTag: string | null
  submitted: number
  failedSubmits: Array<{ displayName: string; message: string }>
  skipped: Array<{ cardId: string; displayName: string; reason: string }>
  cost: number
}

/** 轮询返回（进行中任务的实时状态；批量任务无卡片上下文） */
export interface MockupStatusUpdate {
  taskId: string
  cardId?: string
  groupItemId?: string
  batchTag: string
  status: "queued" | "processing" | "completed" | "failed"
  progress: number
  stage: string | null
  errorMessage: string | null
  resultImage: string | null
}

/** 卡片历史批次 */
export interface MockupHistoryBatch {
  batchTag: string
  createdAt: string
  tasks: Array<{
    taskId: string
    groupItemId: string
    displayName: string
    status: "queued" | "processing" | "completed" | "failed"
    resultImage: string | null
    errorMessage: string | null
    createdAt: string
  }>
}

/** 生成历史记录（按渲染卡片聚合全部生成图片，供「生成历史」视图） */
export interface MockupCardHistoryView {
  cardId: string
  /** 大模板（套组）名 */
  groupName: string
  /** 全部生成图片（仅已出图任务），按生成时间倒序 */
  images: Array<{
    taskId: string
    displayName: string
    resultImage: string
    createdAt: string
  }>
  /** 最近一次出图时间 */
  latestAt: string
  /** 是否有进行中的渲染任务 */
  processing: boolean
}

/* ─── 批量替换 ─── */

/** 批量替换批次列表项（计数由任务实时聚合） */
export interface MockupBatchView {
  id: string
  displayName: string
  totalCount: number
  succeededCount: number
  failedCount: number
  processingCount: number
  createdAt: string
  /** 首张完成图（历史记录封面；列表 action 返回，详情可不带） */
  coverImage?: string | null
}

/** 批量替换任务项 */
export interface MockupBatchTaskView {
  taskId: string
  batchIndex: number
  label: string
  status: "queued" | "processing" | "completed" | "failed"
  progress: number
  stage: string | null
  errorMessage: string | null
  resultImage: string | null
}

/** 批量替换批次详情（含任务明细） */
export interface MockupBatchDetail extends MockupBatchView {
  externalTemplateId: string
  tasks: MockupBatchTaskView[]
}

/** 批量替换页初始数据 */
export interface MockupBatchPageData {
  available: boolean
  costPerRender: number
  creditsBalance: number
}

/** AI 生图任务状态（背景图生成轮询） */
export interface MockupBackgroundTaskView {
  taskId: string
  status: "queued" | "processing" | "completed" | "failed"
  resultImage: string | null
  errorMessage: string | null
}

/** 样机方块 AI 生成结果（AI背景 / AI渲染） */
export interface MockupAiImageView {
  taskId: string
  aiKind: "background" | "render"
  imageUrl: string
  /** 提交 AI 时的渲染图快照（兼作 AI 生成的参考图，可能含前次 AI 背景） */
  refImageUrl: string
  /** 对比视图左侧基准图（纯样机套版渲染，不含任何 AI 结果；缺省回退 refImageUrl） */
  baselineUrl?: string
  /** AI背景落地后重套样机的渲染图（对比视图附加比对项） */
  appliedImageUrl?: string
  prompt: string
  createdAt: string
}
